[project]
name = "python-project-83"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]
